apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-ingress
  namespace: ${namespace}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "syndeno-issuer"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: "python.plt.ko.syndeno.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python
            port:
              number: 5000
        # backend:
        #   service:
        #     name: python
        #     port:
        #       number: 5000
        # path: /
  tls:
    host: ["python.plt.ko.syndeno.net"]
    secret_name: "python.plt.ko.syndeno.net"